-- ============================================================
-- 小桃記帳 × Cherry Daily：全新資料庫「一鍵建置」
-- 使用方式：Supabase → 選到「Cherry Daily」專案 → SQL Editor → New query
--           → 把這整份貼上 → 按 Run（可重複執行）
--
-- 內容：資料表 + 資料隔離(RLS) + 分享/管理員函式 + 即時更新 + 新用戶預設分類
-- 跑完後請另外做：
--   (A) Authentication → Sign In/Providers → Email → 關閉「Confirm email」
--   (B) 把 index.html 的 SUPABASE_KEY 換成本專案的 publishable key
-- ============================================================

-- ── 共用小工具 ──────────────────────────────────────────────
-- 目前登入者的 Email（JWT 內）
create or replace function public.current_email()
returns text language sql stable as $$
  select lower(auth.jwt() ->> 'email');
$$;

-- 是否為管理員（security definer：查 profiles 時略過 RLS，避免遞迴）
-- 用 plpgsql：函式內容延到執行時才解析，避免「建立時 profiles 還沒存在」的錯誤
create or replace function public.is_admin()
returns boolean language plpgsql security definer stable
set search_path = public as $$
begin
  return exists (
    select 1 from public.profiles p
    where p.id = auth.uid() and p.role = 'admin'
  );
end; $$;

-- ── 資料表 ─────────────────────────────────────────────────
-- 個人檔案（一人一列，id = auth 使用者）
create table if not exists public.profiles (
  id         uuid primary key references auth.users(id) on delete cascade,
  email      text,
  username   text,
  birthday   date,
  role       text not null default 'user',     -- user / admin
  status     text not null default 'active',   -- active
  created_at timestamptz not null default now()
);

-- 帳本
create table if not exists public.travel_settings (
  id         bigint generated by default as identity primary key,
  title      text not null default '新帳本',
  tag        text,
  logo       text,
  owner_id   uuid default auth.uid() references auth.users(id) on delete cascade,
  is_daily   boolean default false,
  budget     numeric,
  start_date date,
  end_date   date,
  created_at timestamptz not null default now()
);

-- 消費明細
create table if not exists public.travel_expenses (
  id           bigint generated by default as identity primary key,
  book_id      bigint references public.travel_settings(id) on delete cascade,
  item_name    text,
  amount       numeric,
  currency     text default 'TWD',
  amount_twd   numeric,
  category     text,
  expense_date date,
  day_theme    text,
  is_prepaid   boolean default false,
  is_medical   boolean default false,
  barcode      text,
  created_at   timestamptz not null default now()
);

-- 消費分類（每位使用者各自一份）
create table if not exists public.travel_categories (
  id         bigint generated by default as identity primary key,
  owner_id   uuid default auth.uid() references auth.users(id) on delete cascade,
  name       text not null,
  icon       text default '📦',
  sort       int  default 0,
  created_at timestamptz not null default now()
);

-- 帳本分享
create table if not exists public.book_shares (
  id                bigint generated by default as identity primary key,
  book_id           bigint references public.travel_settings(id) on delete cascade,
  owner_id          uuid default auth.uid() references auth.users(id) on delete cascade,
  shared_with_email text,
  created_at        timestamptz not null default now()
);

-- 全站設定（Logo / 主題色 / 管理員清單，只有一列 id=1）
create table if not exists public.app_settings (
  id          int primary key default 1,
  logo        text,
  theme_color text,
  admin_emails text,
  constraint app_settings_singleton check (id = 1)
);
insert into public.app_settings (id) values (1) on conflict (id) do nothing;

-- ── 啟用 RLS ───────────────────────────────────────────────
alter table public.profiles          enable row level security;
alter table public.travel_settings   enable row level security;
alter table public.travel_expenses   enable row level security;
alter table public.travel_categories enable row level security;
alter table public.book_shares       enable row level security;
alter table public.app_settings      enable row level security;

-- ── 政策（先刪後建，方便重跑）────────────────────────────────
-- profiles：本人可讀寫自己；管理員可讀全部
drop policy if exists "profiles select" on public.profiles;
drop policy if exists "profiles insert" on public.profiles;
drop policy if exists "profiles update" on public.profiles;
create policy "profiles select" on public.profiles for select
  using (id = auth.uid() or public.is_admin());
create policy "profiles insert" on public.profiles for insert
  with check (id = auth.uid());
create policy "profiles update" on public.profiles for update
  using (id = auth.uid() or public.is_admin())
  with check (id = auth.uid() or public.is_admin());

-- travel_settings：擁有者全權；被分享者可讀
drop policy if exists "books owner all"    on public.travel_settings;
drop policy if exists "books shared select" on public.travel_settings;
create policy "books owner all" on public.travel_settings for all
  using (owner_id = auth.uid() or public.is_admin())
  with check (owner_id = auth.uid() or public.is_admin());
create policy "books shared select" on public.travel_settings for select
  using (exists (
    select 1 from public.book_shares s
    where s.book_id = travel_settings.id
      and lower(s.shared_with_email) = public.current_email()
  ));

-- travel_expenses：自己帳本可全權；被分享帳本可讀
drop policy if exists "exp owner all"     on public.travel_expenses;
drop policy if exists "exp shared select" on public.travel_expenses;
create policy "exp owner all" on public.travel_expenses for all
  using (exists (
    select 1 from public.travel_settings b
    where b.id = travel_expenses.book_id
      and (b.owner_id = auth.uid() or public.is_admin())
  ))
  with check (exists (
    select 1 from public.travel_settings b
    where b.id = travel_expenses.book_id
      and (b.owner_id = auth.uid() or public.is_admin())
  ));
create policy "exp shared select" on public.travel_expenses for select
  using (exists (
    select 1 from public.book_shares s
    where s.book_id = travel_expenses.book_id
      and lower(s.shared_with_email) = public.current_email()
  ));

-- travel_categories：每人只看/改自己的
drop policy if exists "cat owner all" on public.travel_categories;
create policy "cat owner all" on public.travel_categories for all
  using (owner_id = auth.uid() or public.is_admin())
  with check (owner_id = auth.uid() or public.is_admin());

-- book_shares：擁有者可管理；被分享者可看到自己那筆
drop policy if exists "shares owner all"        on public.book_shares;
drop policy if exists "shares recipient select" on public.book_shares;
create policy "shares owner all" on public.book_shares for all
  using (owner_id = auth.uid() or public.is_admin())
  with check (owner_id = auth.uid() or public.is_admin());
create policy "shares recipient select" on public.book_shares for select
  using (lower(shared_with_email) = public.current_email());

-- app_settings：任何人可讀（登入頁要用）；只有管理員可改
drop policy if exists "app_settings read"  on public.app_settings;
drop policy if exists "app_settings write" on public.app_settings;
create policy "app_settings read"  on public.app_settings for select using (true);
create policy "app_settings write" on public.app_settings for update
  using (public.is_admin()) with check (public.is_admin());

-- ── 分享帳本（用對方 Email/合成帳號查使用者）────────────────
create or replace function public.share_book(p_book_id bigint, p_email text)
returns text language plpgsql security definer
set search_path = public as $$
declare
  v_owner  uuid;
  v_target uuid;
  v_email  text := lower(trim(p_email));
begin
  select owner_id into v_owner from public.travel_settings where id = p_book_id;
  if v_owner is null then return 'not_owner'; end if;
  if v_owner <> auth.uid() and not public.is_admin() then return 'not_owner'; end if;

  select id into v_target from auth.users where lower(email) = v_email;
  if v_target is null then return 'no_user'; end if;
  if v_target = auth.uid() then return 'self'; end if;

  if exists (select 1 from public.book_shares
             where book_id = p_book_id and lower(shared_with_email) = v_email) then
    return 'ok';
  end if;

  insert into public.book_shares(book_id, owner_id, shared_with_email)
  values (p_book_id, v_owner, v_email);
  return 'ok';
end; $$;

-- ── 管理員刪除使用者（連同其帳本/消費/登入帳號）──────────────
create or replace function public.admin_delete_user(p_uid uuid)
returns text language plpgsql security definer
set search_path = public as $$
begin
  if not public.is_admin() then return 'not_admin'; end if;
  if p_uid = auth.uid()    then return 'cannot_delete_self'; end if;
  delete from public.book_shares where lower(shared_with_email) =
    (select lower(email) from auth.users where id = p_uid);
  delete from auth.users where id = p_uid;   -- cascade 清掉 profiles/books/expenses/categories
  return 'ok';
exception when others then
  return 'error:' || SQLERRM;
end; $$;

-- ── 新使用者自動建立預設分類 ─────────────────────────────────
create or replace function public.seed_user_defaults()
returns trigger language plpgsql security definer
set search_path = public as $$
begin
  insert into public.travel_categories(owner_id, name, icon, sort) values
    (new.id, '餐飲', '🍜', 1), (new.id, '購物', '🛍️', 2),
    (new.id, '交通', '🚗', 3), (new.id, '住宿', '🏨', 4),
    (new.id, '娛樂', '🎡', 5), (new.id, '日常生活', '🏠', 6),
    (new.id, '美妝保養', '💄', 7), (new.id, '其他', '📦', 8);
  return new;
end; $$;
drop trigger if exists on_profile_created on public.profiles;
create trigger on_profile_created after insert on public.profiles
  for each row execute function public.seed_user_defaults();

-- ── 權限 ───────────────────────────────────────────────────
grant execute on function public.current_email()              to anon, authenticated;
grant execute on function public.is_admin()                   to anon, authenticated;
grant execute on function public.share_book(bigint, text)     to authenticated;
grant execute on function public.admin_delete_user(uuid)      to authenticated;
grant all on all tables    in schema public to anon, authenticated;
grant all on all sequences in schema public to anon, authenticated;

-- ── 即時更新（消費明細變動即時同步）──────────────────────────
do $$ begin
  alter publication supabase_realtime add table public.travel_expenses;
exception when duplicate_object then null;
end $$;

notify pgrst, 'reload schema';
